language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: nightly

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - phpenv config-add tests/travis.ini
  - nvm install node

install:
  - composer install --no-interaction
  - bash build/install-travis.sh

script:
  - bash build/build-travis.sh --coverage 1 1

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - travis_retry php coveralls.phar -v --exclude-no-stmt
