language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

services:
  - mysql
  - memcached

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - phpenv config-add tests/travis.ini
  - nvm install node

install:
  - composer install --no-interaction
#  - bash plugins/build/bin/install-travis.sh

script:
  - vendor/bin/phpunit
#  - bash plugins/build/bin/build-travis.sh --coverage 1 1

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - travis_retry php coveralls.phar -v --exclude-no-stmt
