language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer install --prefer-source --no-interaction

script:
  - phpunit --verbose --stderr --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0